import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { Navigation } from '@/app/_navigation'
import { QueryProvider, ThemeProvider } from '@/providers'
import '@/app/globals.css'

export interface Props {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='es' suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <QueryProvider>
            <Navigation>{children}</Navigation>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
