import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { ThemeProvider } from 'next-themes'
import './globals.css'
import { Navigation } from '@/components'

export interface Props {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: Props) {
  return (
    <html lang='es' suppressHydrationWarning>
      <body>
        <ThemeProvider value={{ light: 'light', dark: 'black' }} disableTransitionOnChange>
          <Navigation>{children}</Navigation>
        </ThemeProvider>
      </body>
    </html>
  )
}
