import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import './globals.css'

export interface Props {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: Props) {
  return (
    <html lang='es'>
      <body className='antialiased'>{children}</body>
    </html>
  )
}
